theme: jekyll-theme-minimal

title: Nicholas F Cothard

description: PhD Candidate | Experimental Cosmology | Cornell University | NASA NSTRF Fellow

github: is\_project\_page:false

logo: https://github.com/ncothard/ncothard.github.io/blob/master/Cothard.jpeg?raw=true
