theme: jekyll-theme-minimal

title: Nicholas F Cothard

description: NASA Space Technology Research Fellow and PhD Student at Cornell University working on instrumentation for cosmology and astrophysics observatories.

github: is\_project\_page:false

logo: https://github.com/ncothard/ncothard.github.io/blob/master/headshot_circle.png?raw=true

# Choose Markdown version
markdown: kramdown