theme: jekyll-theme-minimal

title: Nicholas F Cothard

description: Millimeter-wave detectors and interferometers. Ground-based cosmology and astrophysics obervatories. NASA Space Technology Researhc Fellow. PhD candidate at Cornell.

# Millimeter-wave telescope instrumentation for ground-based cosmology and astrophysics obervatories. NASA Space Technology Researhc Fellow. PhD candidate at Cornell.

# PhD Student at Cornell and NASA Space Technology Research Fellow working on telescope instrumentation for cosmology and astrophysics observatories.

github: is\_project\_page:false

logo: https://github.com/ncothard/ncothard.github.io/blob/master/headshot_circle.png?raw=true

google_analytics: UA-179307513-1

# Choose Markdown version
markdown: kramdown

location: "Ithaca, NY"
email: nc467@cornell.edu
twitter: https://twitter.com/NickFCothard
github:
  is_user_page:
  owner_url: https://github.com/ncothard

