theme: jekyll-theme-minimal

title: Nicholas F Cothard

description: PhD Student at Cornell and NASA Space Technology Research Fellow working on telescope instrumentation for cosmology and astrophysics observatories.

github: is\_project\_page:false

logo: https://github.com/ncothard/ncothard.github.io/blob/master/headshot_circle.png?raw=true

# Choose Markdown version
markdown: kramdown