theme: jekyll-theme-minimal

title: Nicholas F Cothard

description: Experimental Cosmology | Cornell University \n PhD Candidate

github: is\_project\_page:false

logo: https://github.com/ncothard/ncothard.github.io/blob/master/headshot_circle.png?raw=true
