theme: jekyll-theme-minimal

title: Nicholas F Cothard

description: PhD Student at Cornell University working on millimeter and far-IR instrumentation for CCAT-prime, Simons Observatory, and ACT telescopes.

github: is\_project\_page:false

logo: https://github.com/ncothard/ncothard.github.io/blob/master/headshot_circle.png?raw=true

# Choose Markdown version
markdown: kramdown